params.author.name: "OSS LATAM"
params.author.bio: "Open Source Latin America."
params.author.avatar: images/author.png
params.author.social.github: opensource-latinamerica
params.author.social.twitter: OpenInfraCDMX
params.author.social.email: hello@oss.lat
params.author.social.youtube: UCpB__-WAEyHdvKAK0Y15akQ
params.author.social.trello: https://trello.com/b/AEpwaRgI
params.author.social.rss: "" # Remove RSS
