name: "OSS LATAM"
bio: "Open Source Latin America."
avatar: images/author.png
social:
  github: opensource-latinamerica
  twitter: OpenInfraCDMX
  email: hello@oss.lat
  youtube: UCpB__-WAEyHdvKAK0Y15akQ
  trello: https://trello.com/b/AEpwaRgI
  rss: "" # Remove RSS
