mainSections:
  - news
  - posts
  - blog
  - events
  - openinfradays

# titleSeparator: '|' # Title separator. Default to -.

description: "Open Infrastructure CDMX User Group focused on community development across Mexico."
keywords: "opensource, latam, community, comunidad"
# metaRobots: noindex, nofollow # Default value for Meta Tag robots
# metaRobots:  # disable Meta Tag robots

logo: "images/author.png"
color: "light"
palettes: []
palette: "white"

# fullWidth: true # Full width.
# fixedHeader: false # Turn on/off fixed header.

dateFormat: ":date_long"

# Google Adsense
googleAdsense: 

# math: true # Enable math globally.
# toc: false # Disable TOC globally.
# tocPosition: content
# breadcrumb: false # Disable breadcrumb
# breadcrumbDivider: > # Breadcrumb divider
# diagram: true
# socialShare: false # disable social network sharing
# searchBar: false # disable search-bar

# poweredBy: false # Whether to show powered by.

# readingTime: false # Whether to display the reading time.
# postDate: false # Whether to display the post date in the post meta section.

# featuredPostCount: 10 # The number of featured posts shown in sidebar. Turn off by setting it to false.
# recentPostCount: 10 # The number of recent posts shown in sidebar. Turn off by setting it to false.
# relatedPostCount: 10 # The number of related posts. Turn off by setting it to false.
# categoryCount: 10 # The number of categories shown in sidebar. Turn off by setting it to false.
# tagCount: 10 # The number of tags shown in sidebar. Turn off by setting it to false.
# seriesCount: 20 # The number of series shown in sidebar. Turn off by setting it to false.
# taxonomyPaginate: 5 # Default to 10.
taxonomyPostCount: 20 # The number of taxonomy's posts. Turn off by setting it to false.
countTaxonomyPosts: true # Count posts of taxonomy.

# sidebarTaxonomies: [categories, tags, series] # The order of taxonomies on the sidebar.
sidebarTaxonomies: ["series", "categories", "tags"]

# pinnedPost: false # Turn on/off pinned posts.
pinnedPostCount: 3 # The number of pinned posts.

# Custom CSS and JS
customCSS:
customJS:

tocWordCount: 1 # TOC is displayed only if the post's word count exceeds this value.

titleCase: true # Capitalized title.

viewer: true # Image Viewer

# backgroundImage: ['/images/bg-light.png', '/images/bg-dark.png']
# rss: home # link the RSS button to homepage all the times.

sidebar:
  # fixed: true
  # archives: true # Enable archives widget
  # taxonomiesToggle: false # Disable taxonomy toggle
  # categories: true # Enable categories widget
  # tags: true # Enable tags widget
  # series: true # Enable series widget
  # authors: true # Enable authors widget
  # postsToggle: false # Disable posts toggle
  # featuredPosts: true # Enable featured posts widget
  # recentPosts: true # Enable featured posts widget
  # collapsed: true # Collapse sidebar widgets by default on small screens.

codeBlock:
  # maxLines: 8
  lineNos: false # true/false represents that show/hide the line numbers by default.

post:
  # excerpt: description
  # excerptMaxLength: 120
  # copyright: false # Whether to display copyright section on each post.
  # plainifyExcerpt: false # Format excerpt in HTML if false.
  featuredImage: true # Show the featured image above the content.
  numberifyHeadings: true # Count headings automatically.
  # numberifyHeadingsEndLevel: 4 # The depth of headings to count. Default to 6.
  numberifyHeadingsSeparator: . # The separator between of number and headings.
  # tocStyleType: decimal # The TOC's CSS list-style-type property.
  # imageTitleAsCaption: true
  # panel: false # Disable the post panel.
  # nav: false # Disable post navigations.
  # The page position after clicking the read more button, read more from content if true. Default to the beginning of page.
  # It supports only of the manual summaries spliting via <!--more-->.
  # readMoreFromContent: true

archive:
  paginate: 20 # Archive pagination. Default to 100.
  # basePath = "/archiv" # The base path of archive pages.
  # dateFormat: 01-02 # Archive date format. Default to Jan 2.

#analytics:
  # baidu:  # Baidu Analytics

# Site verification
#siteVerification:
  #google: 
  #bing: 
  #baidu: 
  #baiduUnion:  # Baidu Union
  #so: 
  #sogou: 
  #shenma: 

creativeCommons:
  nd: true # No derivatives or adaptations of your work are permitted.

# utterances:
  # repo: razonyang/hugo-theme-bootstrap-skeleton # Replace with your repository.
  #issueTerm: pathname # pathname, url, title, og:title
  # label: comment
  # By default, light and dark mode correspond to github-light and github-dark, respectively.
  # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
  #theme:  

#staticman:
  #endpoint: https://yourstaticmaninstance # Required, replace with your own Staticman instance.
  #repo: user/repo # Required
  #service: github # or gitlab. Default to GitHub.
  #branch: main # Default to master.
  #property: comments # Default to comments.
  #sorting: desc # Default to asc.
  #reCaptchaKey: "" # The reCaptcha site key.
  #reCaptchaSecret: "" # The reCaptcha encrypted secret. You'll need to encrypt plain secret via https://yourstaticmaninstance/v3/encrypt/PLAINSECRET.
  #extraFields: # Extra fields. Available fiedls: url.
  #  - url
  #requiredFields: # Extra required fields. Available fields: email and the extra fields.
  #  - email
  #  - url
  #paginate: 5 # Default to 10.
  #moderation: false # Same as Staticman's moderation.

search:
  paginate: 5 # Pagination. Default to 10.
  # resultContentWordCount: 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  case_sensitive: false
  fuse:
    # ignoreLocation: true
    # location: 0
    # isCaseSensitive: false
    # minMatchCharLength: 1
    threshold: 0.1
    # distance: 100
    # useExtendedSearch: true

#docsearch:
  # https://docsearch.algolia.com/docs/api
  # container: ".search-bar" # replace it if necessary, default to '.search-bar'.
  # appId: ""
  # apiKey: ""
  # indexName: ""
  # debug: true

#reward:
  #alipay: images/reward/alipay.png
  #wechat: images/reward/wechat.png
  #paypal: images/reward/paypal.png
  #patreon: images/reward/patreon.png
  #liberapay: images/reward/liberapay.png

#share:
  #addThis:  # AddThis pubid.

#actionsPanel:
  # disabled: true

# Comment or remove this settings to disable font size switcher.
#fontSize:
  # extraSmall: .8rem
  # small: .9rem
  # large: 1.1rem
  # extraLarge: 1.2rem

pwa:
  manifest:
    # name:  # Default to site title.
    short_name: OSSLAT
    # display: fullscreen # Default to standalone.
    # description:  # Default to site description.
    # theme_color: 
    # background_color: 

    # Icons
    # [[pwa.manifest.icons]]
    #   sizes: 96x96
    #   src: /images/icons/icon-96x96.png
    # [[pwa.manifest.icons]]
    #   sizes: 144x144
    #   src: /images/icons/icon-144x144.png

contact:
  custom: true
  provider: "elfsight"
  endpoint: "elfsight-app-8b6b0b6d-11cc-4131-9227-53804eeacfcf"
  file: false # Enable file upload
  # fileField: image # The name of file field.
  # reCaptcha:
    # siteKey: ""

repo:
  url: https://github.com/opensource-latinamerica/osslat
  branch: main

topAppBar:
  social:
    email: hello@oss.lat
    rss: ""

feeds:
  content: false
